FROM node:20.18.1-alpine as build

WORKDIR /app

# Másolás és függőségek telepítése
COPY package*.json ./
RUN npm install

# Alkalmazás másolása
COPY . .

# Alkalmazás build
RUN npm run build

# Kiszolgáló konténer
FROM nginx:alpine

# Másolás a build-ből a webszerverbe
COPY --from=build /app/build /usr/share/nginx/html

# Nginx konfiguráció (opcionális)
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]