version: '3'

services:
  # Backend API service
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: shopping-list-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/shopping-list
      - PORT=5000
    depends_on:
      - mongodb
    networks:
      - shopping-list-network

  # Frontend service
  frontend:
    build:
      context: ./Web
      dockerfile: Dockerfile
    container_name: shopping-list-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - shopping-list-network

  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: shopping-list-mongodb
    restart: unless-stopped
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - mongodb_data:/data/db
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - shopping-list-network
    command: ["--bind_ip", "0.0.0.0"]

networks:
  shopping-list-network:
    driver: bridge

volumes:
  mongodb_data: 